FROM docker.io/ros:humble

# flag to skip keyboard configuration
# prompt while installing xfce
ARG DEBIAN_FRONTEND=noninteractive

# install necessary packages
RUN apt-get update \
    && apt-get install -y \
            ros-${ROS_DISTRO}-desktop \
            # ros-${ROS_DISTRO}-desktop-full \
            # ros-${ROS_DISTRO}-gazebo-ros \
            ros-${ROS_DISTRO}-turtle-tf2-py \
    && rm -rf /var/lib/apt/lists/*
